### ISSUE TITLE
Source input = source output option?

### ISSUE THREAD

**Issue by itsbrex** [danielfrg/demucs-app#2]
Hey Daniel - just tried out the app and it works great!

Curious if it's possible to have it output the same file format as the input? 

i.e. AIFF in --> AIFF out

And perhaps lifting the file size limit? 

Grreat little app!

**Comment by danielfrg** [comment]
The size limit is a constrain of the free hosting I am using but just today i started working on a docker container that will not have this coinstrain so while the app might have it the docker will not.

Other formats is doable but i think demucs recommends mp3.

**Comment by danielfrg** [comment]
I published the docker image today https://hub.docker.com/repository/docker/danielfrg/demucs

This will let you use the app without any size limits. The actual app will have this for the near future mostly because cloudflare where i host my domains has a timeout limit of 100s so i cant change that even if i change the host of the app.
